export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/error/index',
    'pages/component/index/index',
    'pages/component/cover-image/cover-image',
    'pages/component/cover-view/cover-view',
    'pages/component/view/view',
    'pages/component/scroll-view/scroll-view',
    'pages/component/swiper/swiper',
    'pages/component/text/text',
    'pages/component/icon/icon',
    'pages/component/progress/progress',
    'pages/component/button/button',
    'pages/component/checkbox/checkbox',
    'pages/component/form/form',
    'pages/component/input/input',
    'pages/component/label/label',
    'pages/component/picker/picker',
    'pages/component/picker-view/picker-view',
    'pages/component/radio/radio',
    'pages/component/switch/switch',
    'pages/component/textarea/textarea',
    'pages/component/navigator/navigator',
    'pages/component/audio/audio',
    'pages/component/camera/camera',
    'pages/component/image/image',
    'pages/component/video/video',
    'pages/component/live-player/live-player',
    'pages/component/map/map',
    'pages/component/canvas/canvas',
    'pages/component/slider/slider',
    'pages/component/grid-view/grid-view',
    'pages/component/grid-view/demo1',
    'pages/component/grid-view/demo2',
    'pages/component/list-view/list-view',
    'pages/component/page-container/page-container',
    'pages/component/radio-group/radio-group',
    'pages/component/checkbox-group/checkbox-group',
    'pages/component/match-media/match-media',
    'pages/component/movable-view/movable-view',
    'pages/component/sticky-header/sticky-header',
    'pages/component/root-portal/root-portal',
    'pages/component/editor/editor',
    'pages/component/share-element/share-element',
    'pages/api/index/index',
    'pages/api/basics/canIUse/index',
    'pages/api/basics/base64ToArrayBuffer/index',
    'pages/api/basics/getSystemInfo/index',
    'pages/api/basics/getLaunchOptionsSync/index',
    'pages/api/cache/index',
    'pages/api/canvas/index',
    'pages/api/device/clipBoard/index',
    'pages/api/device/network/index',
    'pages/api/device/screen/index',
    'pages/api/device/keyboard/index',
    'pages/api/device/phoneCall/index',
    'pages/api/file/index',
    'pages/api/framework/index',
    'pages/api/interface/interaction/index',
    'pages/api/interface/navigationBar/index',
    'pages/api/interface/font/index',
    'pages/api/interface/pullDownRefresh/index',
    'pages/api/interface/scroll/index',
    'pages/api/interface/animation/index',
    'pages/api/interface/customizedComponents/index',
    'pages/api/interface/menu/index',
    'pages/api/location/index',
    'pages/api/media/image/index',
    'pages/api/media/video/index',
    'pages/api/media/audio/index',
    'pages/api/network/request/index',
    'pages/api/network/download/index',
    'pages/api/network/upload/index',
    'pages/api/network/webSocket/index',
    'pages/api/openAPIS/login/index',
    'pages/api/openAPIS/userInfomation/index',
    'pages/api/openAPIS/setting/index',
    'pages/api/redirection/index',
    'pages/api/routing/index',
    'pages/api/routing/routeA/index',
    'pages/api/taro/expand/index',
    'pages/api/wxml/index',
  ],
  tabBar: {
    color: '#7A7E83',
    selectedColor: '#1F69FF',
    borderStyle: 'black',
    backgroundColor: 'F7F7F7',
    list: [
      {
        pagePath: 'pages/component/index/index',
        iconPath: 'assets/tab/component.png',
        selectedIconPath: 'assets/tab/component_select.png',
        text: '组件',
      },
      {
        pagePath: 'pages/index/index',
        iconPath: 'assets/tab/home.png',
        selectedIconPath: 'assets/tab/home_select.png',
        text: '首页',
      },
      {
        pagePath: 'pages/api/index/index',
        iconPath: 'assets/tab/api.png',
        selectedIconPath: 'assets/tab/api_select.png',
        text: '接口',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F7F7F7',
    navigationBarTitleText: 'Harmony',
    navigationBarTextStyle: 'black',
  },
})
